# opencv-python 基础入门

安装：pip install opencv-python  
导入：import cv2

## 读取图片 cv2.imread()
**原型：**  
 cv2.imread(filename, flags) -> Mat
 
 filename：图片文件的路径。  
 flags: 读取图片的形式，有三种。  
 返回值：一个numpy像素矩阵，失败返回None。  
 
 > 返回的像素矩阵格式为 BGR（红绿蓝）
 
 基本使用示例：

In [2]:
import cv2
import numpy as np

img = cv2.imread('asset/ico.png')
print(img) # 打印像素矩阵

[[[118 118 182]
  [118 118 182]
  [118 118 182]
  ...
  [ 93  99 170]
  [ 93  99 170]
  [ 93  99 170]]

 [[118 118 182]
  [118 118 182]
  [118 118 182]
  ...
  [ 93  99 170]
  [ 93  99 170]
  [ 93  99 170]]

 [[118 118 182]
  [118 118 182]
  [118 118 182]
  ...
  [ 93  99 170]
  [ 93  99 170]
  [ 93  99 170]]

 ...

 [[104  89  80]
  [ 99  84  75]
  [ 90  77  69]
  ...
  [ 51  38 148]
  [ 51  38 148]
  [ 51  38 148]]

 [[104  89  80]
  [100  85  76]
  [ 90  77  69]
  ...
  [ 51  38 148]
  [ 51  38 148]
  [ 51  38 148]]

 [[104  89  80]
  [100  85  76]
  [ 90  77  69]
  ...
  [ 51  38 148]
  [ 51  38 148]
  [ 51  38 148]]]


### flags 参数
- cv2.IMREAD_COLOR    
    读取彩色图片，默认值。等价于 1。
- cv2.IMREAD_GRAYSCALE  
    读取灰度图片，也就是黑白图片。等价于2。
- cv2.IMREAD_UNCHANGED  
    包括 alpha（透明度）。等价于 -1。

示例：

In [3]:
img_color = cv2.imread('asset/ico.png', 1)
assert np.array_equal(img, img_color)

img_gray = cv2.imread('asset/ico.png', cv2.IMREAD_GRAYSCALE)
print(img_gray) # 打印出来的矩阵格式与 img_color 不同

[[141 141 141 ... 125 125 125]
 [141 141 141 ... 125 125 125]
 [141 141 141 ... 125 125 125]
 ...
 [ 89  84  76 ...  90  90  90]
 [ 89  85  76 ...  90  90  90]
 [ 89  85  76 ...  90  90  90]]
